apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-datasource-jaeger
  namespace: monitoring
  labels:
    grafana_datasource: "1"
data:
  jaeger-datasource.yaml: |-
    apiVersion: 1
    datasources:
      - name: Jaeger
        type: jaeger
        uid: jaeger
        access: proxy
        url: http://jaeger-query.jaeger.svc.cluster.local:16686
        isDefault: false
        editable: true
        jsonData:
          httpMethod: GET
          tracesToLogsV2:
            datasourceUid: 'prometheus'
            spanStartTimeShift: '-1h'
            spanEndTimeShift: '1h'
            filterByTraceID: false
            filterBySpanID: false
