apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: monitoring-deploy
  namespace: monitoring
spec:
  interval: 5m0s
  ref:
    branch: main
  timeout: 1m0s
  url: https://github.com/lfarizav/monitoring-deploy.git
