apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: prom
  namespace: monitoring
spec:
  interval: 10m0s
  timeout: 10m0s
  chart:
    spec:
      chart: ./helm/charts/kube-prometheus-stack
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: GitRepository
        name: monitoring-deploy
      version: '*'
  install:
    timeout: 10m0s
    remediation:
      retries: 3
    crds: CreateReplace
  upgrade:
    timeout: 10m0s
    remediation:
      retries: 3
      remediateLastFailure: true
    crds: CreateReplace
    cleanupOnFail: true
  uninstall:
    timeout: 5m
  driftDetection:
    mode: enabled
    ignore:
      - paths: ["/spec/replicas"]
        target:
          kind: Deployment
